%---------------------------------------------------------------------------------------------------
\chapter{Resumen ejecutivo}
\label{chp_res_ejec}

%---------------------------------------------------------------------------------------------------
\section{Definición clara del objeto del estudio}
\label{chp_res_ejec:objeto}
El presente estudio actuarial abarca al Seguro General de Riesgos del Trabajo con fecha de corte 31
de diciembre de 2018, un horizonte de 40 años, cuyo objetivo es evaluar la capacidad del Fondo para
que cumpla con las obligaciones futuras causadas por las contingencias de accidentes de trabajo y 
enfermedades profesionales u ocupacionales en los escenarios económicos, financieros y demográficos 
q